/**
 * Fixture Registry
 *
 * Centralized fixture management for tests.
 */

import type { TestFixtureDescriptor, TestDatasetDescriptor } from '../types';

// Registry of all fixtures
const fixtureRegistry = new Map<string, TestFixtureDescriptor>();
const datasetRegistry = new Map<string, TestDatasetDescriptor>();

/**
 * Register a fixture
 */
export function registerFixture(descriptor: TestFixtureDescriptor): void {
  fixtureRegistry.set(descriptor.name, {
    ...descriptor,
    createdAt: new Date(),
  });
}

/**
 * Get all registered fixtures
 */
export function getRegisteredFixtures(): TestFixtureDescriptor[] {
  return Array.from(fixtureRegistry.values());
}

/**
 * Get fixture descriptor by name
 */
export function getFixtureDescriptor(name: string): TestFixtureDescriptor | undefined {
  return fixtureRegistry.get(name);
}

/**
 * Load fixture by name
 */
export function loadFixture<T = unknown>(name: string, options?: {
  overrides?: Partial<T>;
}): T {
  const fixture = fixtureRegistry.get(name);

  if (!fixture) {
    throw new Error(`Fixture not found: ${name}`);
  }

  if (options?.overrides) {
    return {
      ...(fixture.data as T),
      ...options.overrides,
    } as T;
  }

  return fixture.data as T;
}

/**
 * Validate fixture exists
 */
export function validateFixture(
  name: string,
  options?: { required?: boolean }
): { valid: boolean; error?: string } {
  const exists = fixtureRegistry.has(name);

  if (!exists && options?.required) {
    return {
      valid: false,
      error: `Required fixture not found: ${name}`,
    };
  }

  return { valid: true };
}

/**
 * Register dataset
 */
export function registerDataset(descriptor: TestDatasetDescriptor): void {
  datasetRegistry.set(descriptor.name, descriptor);
}

/**
 * Get dataset by name
 */
export function getDataset(name: string): TestDatasetDescriptor | undefined {
  return datasetRegistry.get(name);
}

/**
 * Get all datasets
 */
export function getRegisteredDatasets(): TestDatasetDescriptor[] {
  return Array.from(datasetRegistry.values());
}

/**
 * Clear all fixtures (for testing)
 */
export function clearFixtures(): void {
  fixtureRegistry.clear();
  datasetRegistry.clear();
}

/**
 * Initialize default fixtures
 */
export function initializeDefaultFixtures(): void {
  // Sample Shopee data fixtures
  registerFixture({
    name: 'shopee-listing-card',
    type: 'sample',
    description: 'Sample Shopee listing card',
    data: {
      itemId: '1234567890',
      name: 'Test Product Name',
      price: 199000,
      originalPrice: 299000,
      discount: 33,
      rating: 4.5,
      reviewCount: 100,
      images: [
        'https://cf.shopee.sg/file/test-image-1',
        'https://cf.shopee.sg/file/test-image-2',
      ],
      shop: {
        shopId: '12345',
        name: 'Test Shop',
        rating: 4.8,
      },
    },
    tags: ['shopee', 'listing', 'sample'],
  });

  registerFixture({
    name: 'shopee-detail-payload',
    type: 'sample',
    description: 'Sample Shopee detail page payload',
    data: {
      itemId: '1234567890',
      name: 'Test Product Detail',
      price: 199000,
      description: 'Product description here',
      images: ['https://cf.shopee.sg/file/detail-1'],
      attributes: {
        brand: 'Test Brand',
        material: 'Cotton',
      },
      options: [
        { name: 'Size', values: ['S', 'M', 'L'] },
        { name: 'Color', values: ['Red', 'Blue'] },
      ],
    },
    tags: ['shopee', 'detail', 'sample'],
  });

  // AI output fixtures
  registerFixture({
    name: 'ai-enriched-content',
    type: 'sample',
    description: 'Sample AI enriched content',
    data: {
      hashtags: ['fashion', 'style', 'ootd', 'shopping'],
      description: 'This is a sample product description generated by AI',
      title: 'Enhanced Test Product Title',
      tags: ['sample', 'test', 'ai'],
      meta: {
        model: 'gemini-1.5-pro',
        promptVersion: 'v1.0',
        timestamp: '2024-01-01T00:00:00Z',
      },
    },
    tags: ['ai', 'enrichment', 'sample'],
  });

  // Publish job fixtures
  registerFixture({
    name: 'publish-job-pending',
    type: 'sample',
    description: 'Sample pending publish job',
    data: {
      id: 'job-test-123',
      productId: 'product-456',
      channel: 'tiktok',
      status: 'pending',
      payload: {
        video: 'https://example.com/video.mp4',
        caption: 'Check out this product!',
      },
      attempts: 0,
      maxAttempts: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    tags: ['publishing', 'job', 'sample'],
  });

  registerFixture({
    name: 'publish-job-completed',
    type: 'sample',
    description: 'Sample completed publish job',
    data: {
      id: 'job-test-124',
      productId: 'product-457',
      channel: 'facebook',
      status: 'completed',
      payload: {
        postId: 'fb-post-123',
        postUrl: 'https://facebook.com/post/123',
      },
      attempts: 1,
      maxAttempts: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    tags: ['publishing', 'job', 'completed'],
  });

  // Database fixtures
  registerFixture({
    name: 'affiliate-product-record',
    type: 'fixture',
    description: 'Sample affiliate product database record',
    data: {
      id: 'prod-001',
      sourceId: 'shopee-123',
      source: 'shopee',
      name: 'Sample Affiliate Product',
      url: 'https://shopee.vn/product/123',
      imageUrl: 'https://cf.shopee.sg/file/image.jpg',
      price: 199000,
      commission: 10,
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    tags: ['database', 'product', 'affiliate'],
  });

  // Mock API responses
  registerFixture({
    name: 'gemini-success-response',
    type: 'mock',
    description: 'Mock Gemini API success response',
    data: {
      candidates: [
        {
          content: {
            parts: [
              {
                text: JSON.stringify({
                  hashtags: ['fashion', 'style'],
                  description: 'Sample description',
                  title: 'Enhanced title',
                }),
              },
            ],
          },
        },
      ],
    },
    tags: ['mock', 'gemini', 'api'],
  });

  registerFixture({
    name: 'gemini-error-response',
    type: 'mock',
    description: 'Mock Gemini API error response',
    data: {
      error: {
        code: 400,
        message: 'Invalid request',
        status: 'INVALID_ARGUMENT',
      },
    },
    tags: ['mock', 'gemini', 'error'],
  });

  // Health check responses
  registerFixture({
    name: 'health-liveness-response',
    type: 'mock',
    description: 'Mock health liveness response',
    data: {
      status: 'healthy',
      timestamp: new Date().toISOString(),
    },
    tags: ['mock', 'health'],
  });

  registerFixture({
    name: 'health-readiness-response',
    type: 'mock',
    description: 'Mock health readiness response',
    data: {
      ready: true,
      checks: [
        { name: 'database', status: 'healthy' },
        { name: 'workers', status: 'healthy' },
      ],
      timestamp: new Date().toISOString(),
    },
    tags: ['mock', 'health'],
  });
}

// Auto-initialize
initializeDefaultFixtures();
